/**
 * Pentagon numbers
 *
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
 * pentagonal numbers are: 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
 * 70 − 22 = 48, is not pentagonal.
 *
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
 * difference are pentagonal and D = |Pk − Pj| is minimised; what is the value
 * of D?
 *
 * Strategy: brute force
 * Source: https://projecteuler.net/problem=44
 * Result: 5482660
 * Time: 53s
 */

var pentagons = [];
var pentagonsNumber = 3000;

for (var n = 1; n < pentagonsNumber; n++) pentagons.push(n * (3 * n - 1) / 2);

/**
 * @param {number} n
 * @return {boolean}
 */
function isPentagonal(n)
{
  return pentagons.indexOf(n) != -1;
}

var D = Infinity;
var d = 0;

for (var i = 0; i < pentagonsNumber; i++)
  for (var j = 0; j < pentagonsNumber; j++)
    if (isPentagonal(pentagons[i] + pentagons[j])) {
      d = Math.abs(pentagons[i] - pentagons[j]);

      if (isPentagonal(d)) D = Math.min(D, d);
    }

self.postMessage('Minimal adjacent pentagonal number difference: ' + D, []);
