/**
 * Pentagon numbers
 *
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten
 * pentagonal numbers are: 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
 * 70 − 22 = 48, is not pentagonal.
 *
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
 * difference are pentagonal and D = |Pk − Pj| is minimised; what is the value
 * of D?
 *
 * Strategy: brute force
 * Source: https://projecteuler.net/problem=44
 * Result: 5482660
 * Time: 53s
 */
'use strict';

const pentagons = [];
const pentagonsNumber = 3000;

for (let n = 1; n < pentagonsNumber; n++) pentagons.push(n * (3 * n - 1) / 2);

/**
 * @param {number} n
 * @return {boolean}
 */
function isPentagonal(n) {
  return (pentagons.indexOf(n) !== -1);
}

let D = Number.POSITIVE_INFINITY;
let d = 0;

for (let i = 0; i < pentagonsNumber; i++) {
  for (let j = 0; j < pentagonsNumber; j++) {
    if (isPentagonal(pentagons[i] + pentagons[j])) {
      d = Math.abs(pentagons[i] - pentagons[j]);

      if (isPentagonal(d)) D = Math.min(D, d);
    }
  }
}

console.log('Minimal adjacent pentagonal number difference', D);
