/**
 * Pentagon numbers
 *
 * Pentagonal numbers are generated by the formula, P(n) = n*(3n−1)/2. The first
 * ten pentagonal numbers are: 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference,
 * 70 − 22 = 48, is not pentagonal.
 *
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and
 * difference are pentagonal and D = |Pk − Pj| is minimized; what is the value
 * of D?
 *
 * @see {@link https://projecteuler.net/problem=44}
 * Solution: 5482660
 */
'use strict';

const pentagons = [];
const pentagonsNumber = 3000;

for (let n = 1; n < pentagonsNumber; n++) pentagons.push(n * (3 * n - 1) / 2);

let D = Number.POSITIVE_INFINITY;
let d = 0;

for (let i = 0; i < pentagonsNumber; i++) {
  for (let j = 0; j < pentagonsNumber; j++) {
    if (pentagons.includes(pentagons[i] + pentagons[j])) {
      d = Math.abs(pentagons[i] - pentagons[j]);

      if (pentagons.includes(d)) D = Math.min(D, d);
    }
  }
}

console.log('Minimal adjacent pentagonal number difference', D);
