/**
 * Triangular, pentagonal, and hexagonal
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following
 * formulae:
 * Triangle      Tn=n(n+1)/2       1, 3, 6, 10, 15, ...
 * Pentagonal      Pn=n(3n−1)/2      1, 5, 12, 22, 35, ...
 * Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...
 *
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 * Strategy: brute force
 * Source: https://projecteuler.net/problem=45
 * Result: 1533776805
 * Time: 17s
 */

var T = [];
var P = [];
var H = [];

for (var i = 0; i < 100000; i++) {
  T[i] = i * (i + 1) / 2;
  P[i] = i * (3 * i - 1) / 2;
  H[i] = i * (2 * i - 1);
}

var TPH = T.filter(function(e) { return P.indexOf(e) != -1; })
           .filter(function(e) { return H.indexOf(e) != -1; });

self.postMessage('TPH: ' + TPH.join('; '), []);
